version: '3.8'
services:
  # server:
  #   build: .
  #   container_name: portfolio-backend
  #   command: npm run start:dev
  #   volumes:
  #     - .:/usr/src/app
  #   ports:
  #     - '8000:8000'
  #   depends_on:
  #     - db
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_NAME}
    container_name: 'portfolio-db-container'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - '5431:5432'
  pg4:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - '80:80'

volumes:
  postgres:
